# Generated by Django 4.2.27 on 2026-01-08 12:01

import apps.storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_file_folder_folder_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                upload_to=apps.storage.models.user_file_path
            ),
        ),
    ]
